### ISSUE TITLE
Include JS References on index.html [BlazorWASM]

### ISSUE THREAD

**Issue by mcmpistachio** [Blazorade/Blazorade-Teams#11]
I'm trying to wire up the Blazorade Teams NuGet and the app is acting like its not authenticating. In the documentation it doesn't have adding the 2 javascript references to the index.html like the package reference project does. 

Are they no longer needed? If they are I'm guessing they'd need to look like 

><script src="https://statics.teams.cdn.office.net/sdk/v1.7.0/js/MicrosoftTeams.min.js"></script> <br />
><script src="_content/BlazoradeTeams/js/blazoradeTeams.js"></script><br />
><script src="_content/BlazoradeTeams/js/blazoradeMsal.js></script>

**Comment by MikaBerglund** [comment]
That's true. You don't need to add the reference to those scripts. They are dynamically imported in the component code in [`InteropModuleBase`](https://github.com/Blazorade/Blazorade-Teams/blob/master/Blazorade.Teams/Interop/InteropModuleBase.cs).

Have you [registered your your application with Azure AD](https://github.com/Blazorade/Blazorade-Teams/wiki/Getting-Started-Register-Application)? Have you set the `RequireAuthentication` parameter to `true` on [`TeamsApplication`](https://github.com/Blazorade/Blazorade-Teams/wiki/TeamsApplication)?

If you are running your application in the Teams client, it will not work for the moment. I just noticed that myself. I will be filing an issue about that, and it will be fixed before releasing v1.0.

**Comment by MikaBerglund** [comment]
The bug has now been created: #12 .

**Comment by mcmpistachio** [comment]
I've registered the app with AAD it is set to true. Teams Online is giving the same error. 

Is Teams SSO a possibility to circumvent the MSAL popup?

**Comment by MikaBerglund** [comment]
Seems that the MSAL popup is the culprit here. It should be implemented using the [authentication](https://docs.microsoft.com/javascript/api/@microsoft/teams-js/authentication) module in Teams SDK.

**Comment by MikaBerglund** [comment]
Just to let you know, I'm working on this issue #12 that should solve also your problem. I will close this issue as it is being followed up on in #12. Feel free to add any comments to this issue if you need to.
