### ISSUE TITLE
Authentication does not work in Teams desktop client

### ISSUE THREAD

**Issue by MikaBerglund** [Blazorade/Blazorade-Teams#12]
If you have an application that requires authentication (setting `RequireAuthentication="true"` on [`TeamsApplication`](https://github.com/Blazorade/Blazorade-Teams/wiki/TeamsApplication)), the authentication does not work when the application is running in the Teams desktop client.

The problem seems to be that `loginPopup` in MSAL does not work in the desktop client. We need to change the popup to use the built-in popup in Teams and follow the principles in the [PnP sample](https://github.com/pnp/teams-dev-samples/tree/master/samples/tab-aad-msal2).

**Comment by odonnell-pb** [comment]
@MikaBerglund I have just got this working with both the desktop and web client using SSO for Tabs per [Single sign-on (SSO) support for tabs](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso). 

I have a bit of tidying up to do, but, if you're interested I will create a PR for you to review and comment on.

BTW great work on getting this project up and running - if you want any help let me know.

**Comment by MikaBerglund** [comment]
Sure! I'll be happy to get your PR. I'm working on a solution too, but it is still quite early, so I'll appreciate any help.

The problem with the SSO solution supported by Teams is that you can only acquire access tpkens to Microsoft Graph to a very limited set of scopes. I would like to be able to acquire tokens to any API and any scopes. 

But send me the PR and we'll take it from there.
