### ISSUE TITLE
Not possible to initialize without an app id

### ISSUE THREAD

**Issue by tfenster** [Blazorade/Blazorade-Teams#21]
There seems to be a problem if you try to use Blazorade Teams without an app id as explained [here](https://github.com/Blazorade/Blazorade-Teams/wiki/Getting-Started-Wiring-Up#add-blazor-teams-services-in-startup). E.g. if I use the serverside sample app and change this (from [here](https://github.com/Blazorade/Blazorade-Teams/blob/fbd5986c9ad43557116a22b02845041d36ecfac0/Samples/TeamsTabAppServer/Startup.cs#L25-L35))

```
.AddBlazoradeTeams((p, c) =>
  {
      var root = p.GetService<IConfiguration>();
      var config = root.GetSection("teamsApp");
      c.ClientId = config.GetValue<string>("clientId");
      c.TenantId = config.GetValue<string>("tenantId");

      c.LoginUrl = "/login";

      c.DefaultScopes = new string[] { "User.Read" };
  });
```

to

```
.AddBlazoradeTeams();
```

I run into 

```
Exception has occurred: CLR/System.AggregateException
An unhandled exception of type 'System.AggregateException' occurred in Microsoft.Extensions.DependencyInjection.dll: 'Some services are not able to be constructed'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.InvalidOperationException : Unable to resolve service for type 'Blazorade.Teams.Configuration.BlazoradeTeamsOptions' while attempting to activate 'Blazorade.Teams.Interop.BlazoradeTeamsInteropModule'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
...
```

Am I missing something?

**Comment by MikaBerglund** [comment]
Thanks for reporting! Seems that I have missed something there. Although, in order to authenticate the user with oauth and open ID, you would always need an application ID. Still, I guess there might be scenarios where you don't need to authenticate the user, or maybe authenticate using some proprietary mechanism, so configuring your Teams app without an application ID should definitely be possible. And it should be done as you've tried to do it, just using `.AddBlazoradeTeams()`.

I've filed this as a bug that I'll be investigating. It will be resolved before the first stable release.

**Comment by MikaBerglund** [comment]
Seems that there is in fact a bug that causes this. I'll start working on a fix right away.

**Comment by tfenster** [comment]
@MikaBerglund Thanks a lot! Let me know if I can help in any way

**Comment by MikaBerglund** [comment]
No problem. I am working on a fix right now. Shouldn't be that big of a thing to fix. Just something that I completely missed. You can at least help by verifying that the fix works as expected, once I get it published.

**Comment by tfenster** [comment]
I'll certainly do that. Thanks a lot for your great work, very much appreciated!

**Comment by MikaBerglund** [comment]
OK, so this bug is now fixed. The release notes are [available here](https://github.com/Blazorade/Blazorade-Teams/releases/tag/v1.0.0-rc-06).

I also published a new version on Nuget. I guess it will be visible shortly.

Thanks again for reporting this! Much appreciated!

**Comment by MikaBerglund** [comment]
And please note that there is a small breaking change with the fix.
