### ISSUE TITLE
Issues with Authentication

### ISSUE THREAD

**Issue by greg-dickie** [Blazorade/Blazorade-Teams#22]
Let me say first that I'm new to both Teams and Blazor development.  I'm trying to use Blazorade.Teams with Blazor WASM to also access a Server Side Web API that is secured with Azure AD.  The authentication dialog appears when I open my tab in Teams but I get an error in the browser console "Value cannot be null. (Parameter 'json') in the blazoradeTeams.js file.  I have downloaded the sample and it works properly so I know it is something that I'm doing wrong on my side, I just can't figure out what that would be.

Here is my Program.cs:
`
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("#app");

            builder.Services.AddBlazoradeTeams((provider, config) =>
            {
                var myTeamsApp = provider
                    .GetService<IConfiguration>()
                    ?.GetSection("myTeamsApp");
                config.ClientId = myTeamsApp.GetValue<string>("clientId");
                config.TenantId = myTeamsApp.GetValue<string>("tenantId");

                config.LoginUrl = "/login";
                config.DefaultScopes = new string[] { "User.Read" };
            });

            builder.Services.AddHttpClient("Forms.Web.ServerAPI", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
                .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();

            // Supply HttpClient instances that include access tokens when making requests to the server project
            builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("Forms.Web.ServerAPI"));

            builder.Services.AddMsalAuthentication(options =>
            {
                builder.Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
                options.ProviderOptions.DefaultAccessTokenScopes.Add("api://{Client ID}/API.Access");
                //options.ProviderOptions.LoginMode = "redirect";
            });

            await builder.Build().RunAsync();
`
Thanks for any help you can give,
Greg

**Comment by MikaBerglund** [comment]
Thanks for this Greg!

Actually, Blazorade Teams should be able to take care of the authentication for. You would just need to add your custom API scope(s) to the default scopes configured for Blazorade Teams (or specify them as parameters on the [`TeamsApplication`](https://github.com/Blazorade/Blazorade-Teams/wiki/TeamsApplication) component in your application, using the `RequireScopes` parameter).

Using MSAL as in any normal web application will work in Teams only when you run Teams in the Browser. But when you use the desktop client or the mobile clients, that won't work if you don't wire up the authentication dialog that the Teams SDK provides.

That's why also authentication is handled by the TeamsApplication component for you, and you only need to do some minimal configuration in the `.AddBlazoradeTeams` method.

Did you already try [this demo script](https://mikaberglund.com/pnp-dev-general-community-call-demo-feb-4-2021/) that I published on my blog? That is the script to a demo I did in a PnP Community Call a while ago. Just change the configuration in Startup to the code below (there might be some typos in this, because I just wrote it here in my reply).

``` C#
services.AddBlazoradeTeams((sp, options) =>
{
    var root = sp.GetService<IConfiguration>();
    var config = root.GetSection("teamsApp");
    config.Bind(options);

    options.LoginUrl = "/login";
    options.DefaultScopes = new string[] { "User.Read", $"api://{options.ClientId}/API.Access" };
});
```

Let me know how it goes. If you don't get it working, then let's try something else. OK?

**Comment by greg-dickie** [comment]
Hi Mika,

Sorry it has taken me so long to respond, last week was crazy and I didn’t get a chance to look at this.  I’m getting back up to speed with what I have tried and basically all that I need in my application through Teams is the UPN.  This will allow me to verify that the user that is logged in to teams has permission to use my app.

Do I need to implement authentication to get the UPN?

Thanks for the help,
Greg

From: Mika Berglund ***@***.***>
Date: Saturday, March 13, 2021 at 6:25 AM
To: Blazorade/Blazorade-Teams ***@***.***>
Cc: Greg Dickie ***@***.***>, Author ***@***.***>
Subject: Re: [Blazorade/Blazorade-Teams] Issues with Authentication (#22)

Thanks for this Greg!

Actually, Blazorade Teams should be able to take care of the authentication for. You would just need to add your custom API scope(s) to the default scopes configured for Blazorade Teams (or specify them as parameters on the TeamsApplication<https://github.com/Blazorade/Blazorade-Teams/wiki/TeamsApplication> component in your application, using the RequireScopes parameter).

Using MSAL as in any normal web application will work in Teams only when you run Teams in the Browser. But when you use the desktop client or the mobile clients, that won't work if you don't wire up the authentication dialog that the Teams SDK provides.

That's why also authentication is handled by the TeamsApplication component for you, and you only need to do some minimal configuration in the .AddBlazoradeTeams method.

Did you already try this demo script<https://mikaberglund.com/pnp-dev-general-community-call-demo-feb-4-2021/> that I published on my blog? That is the script to a demo I did in a PnP Community Call a while ago. Just change the configuration in Startup to the code below (there might be some typos in this, because I just wrote it here in my reply).

services.AddBlazoradeTeams((sp, options) =>

{

    var root = sp.GetService<IConfiguration>();

    var config = root.GetSection("teamsApp");

    config.Bind(options);



    options.LoginUrl = "/login";

    options.DefaultScopes = new string[] { "User.Read", $"api://{options.ClientId}/API.Access" };

});

Let me know how it goes. If you don't get it working, then let's try something else. OK?

**Comment by MikaBerglund** [comment]
Hi Greg!

The user principal name provided in the context from Teams (through Blazorade Teams) should only be considered as a hint, but not rely on it completely without proper authentication.

https://docs.microsoft.com/javascript/api/@microsoft/teams-js/context#userPrincipalName

**Comment by greg-dickie** [comment]
Thanks Mika. I’ve got it configured to authenticate properly with Blazor Server now.

Greg
________________________________

**Comment by MikaBerglund** [comment]
Great. I guess I can close the issue now then?

**Comment by greg-dickie** [comment]
Yes, thanks again for your help.

Greg
________________________________
